import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header, Sidebar } from "../components/layout";
import { ConditionalLayout } from "../components/ConditionalLayout";
import { LoadingProvider } from "../components/providers/LoadingProvider";
import AuthGuard from "../components/auth/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AdminHub - Dashboard SaaS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-Br" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212] text-white`}
      >
        <LoadingProvider>
          <AuthGuard>
            <ConditionalLayout>
              {children}
            </ConditionalLayout>
          </AuthGuard>
        </LoadingProvider>
      </body>
    </html>
  );
}
